[package]
name = "coap_test01"
version = "0.1.1"
authors = ["Erik Moden <erik.moden@labgruppen.com>"]
edition = "2018"

[dependencies]
structopt = "^0.2.10"
coap = "0.7"
failure = "^0.1.5"
exitfailure = "^0.5.1"
serde_cbor = "^0.9.0"
serde_json = "^1.0.39"
serde-transcode = "^1.1.0"
num-traits = "^0.1.43"
